from core.llm import LLMProvider
from core.diplomat.psych_profile import profiler
from core.security.neuro_crypt import shield
import json

class DigitalSteganography:
    """
    Injects Invisible Watermarks into text.
    Encodes the Hardware ID into Zero-Width Characters.
    Anti-Copy Safety: Traces origin of ANY text generated by this Diplomat.
    """
    def __init__(self):
        self.hw_id = shield._fingerprint 
        
    def inject_watermark(self, text):
        # Convert HW ID hash (hex) to binary
        binary = bin(int(self.hw_id, 16))[2:]
        
        # Map 0 -> \u200b (Zero Width Space), 1 -> \u200c (Zero Width Non-Joiner)
        watermark = ""
        for bit in binary:
            watermark += "\u200b" if bit == '0' else "\u200c"
            
        # Append to end of text
        return text + watermark

class DiplomatEngine:
    def __init__(self):
        shield.check_integrity() # Ensure we are on valid hardware
        self.llm = LLMProvider()
        self.watermarker = DigitalSteganography()
        
    def formulate_argument(self, goal, target_text_sample=None):
        """
        Creates a highly persuasive argument tailored to the target.
        """
        # 1. Profile Target
        strategy = "LOGOS"
        if target_text_sample:
            analysis_str = profiler.analyze_profile(target_text_sample)
            try:
                # simpler parsing if it's a string
                if isinstance(analysis_str, str) and "{" in analysis_str:
                     import json
                     data = json.loads(analysis_str[analysis_str.find("{"):analysis_str.rfind("}")+1])
                     strategy = data.get('strategy', 'LOGOS')
            except: pass
            
        # 2. Generate Argument
        prompt = f"""
        [Persuasion Task]
        Goal: {goal}
        Target Profile Strategy: {strategy}
        
        Write a persuasive message/email to achieve the goal. 
        Use the {strategy} approach strictly.
        """
        raw_text = self.llm.generate_text(prompt)
        
        # 3. Apply Safety Watermark (Deep Feature)
        final_text = self.watermarker.inject_watermark(raw_text)
        
        return final_text, strategy

    def negotiate_rate_limit(self, api_name):
        """
        Specialized logic for negotiating with API providers.
        """
        # Hardcoded 'Corporate Diplomat' persona
        prompt = f"""
        Write a professional request to {api_name} support.
        Goal: Increase API Rate Limits for an AI Research Project.
        Tone: Professional, Innovative, Responsible.
        Include: 'We are implementing strict safety guardrails.'
        """
        raw = self.llm.generate_text(prompt)
        return self.watermarker.inject_watermark(raw)

# Singleton
diplomat = DiplomatEngine()
