
import importlib
import sys
import threading

class CapabilityManager:
    _instance = None
    _lock = threading.Lock()
    
    def __new__(cls):
        with cls._lock:
            if cls._instance is None:
                cls._instance = super(CapabilityManager, cls).__new__(cls)
                cls._instance.layers = {}
                cls._instance.loaded_libs = set()
        return cls._instance

    def load_layer(self, layer_name):
        """Lazy load a capability layer."""
        if layer_name in self.layers:
            return self.layers[layer_name]
        
        print(f"[CapabilityManager] Loading Layer: {layer_name}...")
        
        try:
            if layer_name == "DataLayer":
                self.layers[layer_name] = self._init_data_layer()
            elif layer_name == "DocLayer":
                self.layers[layer_name] = self._init_doc_layer()
            elif layer_name == "KnowledgeLayer":
                self.layers[layer_name] = self._init_knowledge_layer()
            elif layer_name == "AutomationLayer":
                self.layers[layer_name] = self._init_automation_layer()
            elif layer_name == "VisionLayer":
                self.layers[layer_name] = self._init_vision_layer()
            else:
                raise ValueError(f"Unknown layer: {layer_name}")
            
            print(f"[CapabilityManager] Layer {layer_name} READY.")
            return self.layers[layer_name]
        except ImportError as e:
            print(f"[CapabilityManager] FAILED to load {layer_name}: {e}")
            return None
        except Exception as e:
            print(f"[CapabilityManager] Error loading {layer_name}: {e}")
            return None

    def _init_data_layer(self):
        """Pandas, NumPy, Matplotlib, SQL"""
        import pandas as pd
        import numpy as np
        import matplotlib.pyplot as plt
        import sqlalchemy
        
        class DataLayer:
            def analyze_csv(self, filepath, query):
                df = pd.read_csv(filepath)
                return f"Loaded CSV with shape {df.shape}. Columns: {list(df.columns)}"
            
            def analyze_with_pandas_agent(self, df, query):
                # Placeholder for Pandas Agent logic
                return "Pandas agent analysis not fully linked yet."
                
        return DataLayer()

    def _init_doc_layer(self):
        """Python-docx, Python-pptx, ReportLab"""
        import docx
        import pptx
        from reportlab.pdfgen import canvas
        
        class DocLayer:
            def create_word_doc(self, filename, content):
                doc = docx.Document()
                doc.add_paragraph(content)
                doc.save(filename)
                return f"Word doc saved to {filename}"
                
            def create_ppt(self, filename, title, slides_content):
                prs = pptx.Presentation()
                
                # 1. Title Slide
                title_slide_layout = prs.slide_layouts[0]
                slide = prs.slides.add_slide(title_slide_layout)
                slide.shapes.title.text = title
                slide.placeholders[1].text = "Generated by Omniagent v2.5 | Horizon Stack"

                # 2. Content Slides
                bullet_slide_layout = prs.slide_layouts[1] # Title and Content
                
                for slide_data in slides_content:
                    if isinstance(slide_data, str):
                        # Simple string case
                        s = prs.slides.add_slide(bullet_slide_layout)
                        s.shapes.title.text = "Info"
                        s.placeholders[1].text = slide_data
                    elif isinstance(slide_data, dict):
                        # Structured dict case
                        s = prs.slides.add_slide(bullet_slide_layout)
                        s.shapes.title.text = slide_data.get('slide_title', slide_data.get('title', 'Untitled'))
                        
                        # Handle body text or bullet points
                        tf = s.placeholders[1].text_frame
                        tf.text = slide_data.get('text', '')
                        
                        bullets = slide_data.get('bullet_points', [])
                        if bullets:
                            if not tf.text: tf.text = bullets[0]
                            else: 
                                p = tf.add_paragraph()
                                p.text = bullets[0]
                                
                            for b in bullets[1:]:
                                p = tf.add_paragraph()
                                p.text = b

                prs.save(filename)
                return f"Presentation saved to {filename} with {len(prs.slides)} slides."
        
        return DocLayer()

    def _init_knowledge_layer(self):
        """LangChain, LlamaIndex, FAISS, Transformers"""
        # We import these HEAVY libs only here
        from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
        import faiss
        
        class KnowledgeLayer:
            def index_folder(self, folder_path):
                documents = SimpleDirectoryReader(folder_path).load_data()
                index = VectorStoreIndex.from_documents(documents)
                return index
                
            def query_index(self, index, query):
                query_engine = index.as_query_engine()
                return str(query_engine.query(query))
        
        return KnowledgeLayer()

    def _init_automation_layer(self):
        """Prefect, Celery, Redis, Schedule"""
        import prefect
        import celery
        import redis
        import schedule
        
        class AutomationLayer:
            def schedule_task(self, task_func, time_str):
                schedule.every().day.at(time_str).do(task_func)
                return f"Task scheduled for {time_str}"
        
        return AutomationLayer()

    def _init_vision_layer(self):
        """OpenCV, Pillow, ResNet"""
        import cv2
        from PIL import Image
        
        class VisionLayer:
            def process_image(self, image_path):
                img = cv2.imread(image_path)
                return f"Image loaded. Shape: {img.shape}"
        
        return VisionLayer()

# Global Instance
capability_manager = CapabilityManager()
