[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "horizondesk-sdk"   # change name (important)
version = "1.2.0"                 # bump version
authors = [
    { name="Rapnss Team", email="admin@rapnss.in" },
]
description = "SDK and CLI for building Horizon Desk AI Plugins"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests",
    "pywebview",
    "colorama",
    "python-dotenv",
    "psutil"
]

[project.scripts]
horizondesk-sdk = "horizondesk_sdk.cli:main"

[project.urls]
Homepage = "https://github.com/rapnss/horizondesk-sdk"
Issues = "https://github.com/rapnss/horizondesk-sdk/issues"

[tool.setuptools.packages.find]
where = ["."]